import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/components/theme-provider';
import Nav from '@/components/navbar';
import SideBar from '@/components/Sidbar';
import { Sidebarprovider } from '@/Context/SidebarContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Youtube',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

         <Sidebarprovider>
         <div className='flex flex-col'>
            <Nav />
            <div className='flex'>
             <div>
             <SideBar />
             </div>
              {children}
            </div>
          </div>
          </Sidebarprovider>
        </ThemeProvider>
      </body>
    </html>
  );
}